### PR TITLE
example -> embedded val

### PR DESCRIPTION
**Pull request by stevekrouse**
I don't know how to preview changes like this in your stack, but I wanted to propose embedded vals as an option :)

### CODE REVIEW

**Review by whatrocks — APPROVED** [review]
Love this. Sorry for the very long code-review process, haha.

**Comment by stevekrouse** [comment]
Cool! I think we got into a little trouble for not previewing first:

Screenshot 2024-07-15 at 09 27 20@2x

**Comment by whatrocks** [comment]
> Cool! I think we got into a little trouble for not previewing first:
> 
> Screenshot 2024-07-15 at 09 27 20@2x

Ah, yeah. I YOLO'ed. Just pushed up a fix!

**Comment by stevekrouse** [comment]
Looks great!

**Pull request merged**
